---
- name: Create file on device
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:
    - name: Create configuration file
      ansible.netcommon.cli_command:
        command: |
          configure terminal
          file prompt quiet
          end

    - name: Write content to file
      ansible.netcommon.cli_config:
        config: |
          hostname {{ inventory_hostname }}
          banner motd "Archivo creado por Ansible"
        save_when: modified   