---
- name: AWX + NetBox Dynamic Inventory Demo
  hosts: all
  gather_facts: false

  tasks:        
    - name: Create file
      raw: 'echo "AWX Demo - {{ inventory_hostname }} - {{ ansible_host }}" > /tmp/awx-demo-{{ inventory_hostname }}.txt'

    - name: Show result
      debug:
        msg: "{{ inventory_hostname }} ({{ ansible_host }}): {{ file_content.stdout }}"
